[package]
name = "displays-controller-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
enigo = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tiny_http = "0.12"
rdev = "0.5"
ctrlc = "3"
